# DOCKERFILE FOR DISTILLER

FROM tensorflow/tensorflow:1.7.0-gpu-py3

ENV SHELL=/bin/bash
ARG DEFAULT_WORKDIR=/workspace

RUN apt-get update && apt-get install -y \      
        bsdmainutils \  
        git \
        graphviz \
        less \
        nano \
        vim \
        wget && \        
    rm -rf /var/lib/apt/lists/*
    
RUN git clone https://github.com/nervanasystems/distiller && \
    cd distiller && \
    pip3 install -r requirements.txt && \
    pip3 install git+https://github.com/szagoruyko/pytorchviz \
    pretrainedmodels \
    tqdm
    
RUN jupyter nbextension enable --py widgetsnbextension --sys-prefix

WORKDIR $DEFAULT_WORKDIR
RUN rm -rf distiller   

WORKDIR /home
